### ISSUE TITLE
Hi~ May I ask if there is any code related to the paper “geometric images” ？

### ISSUE THREAD

**Issue by IntegralCoCo** [hhoppe/Mesh-processing-library#2]
Hi~ May I ask if there is any code related to the paper “geometric images” ？

**Comment by hhoppe** [comment]
Thanks for your interest.  Unfortunately the "geometry images" code is unavailable.

**Comment by ZiDion** [comment]
https://users.csc.calpoly.edu/~zwood/teaching/csc570/final07/dalum_gzipkin/

**Comment by IntegralCoCo** [comment]
> https://users.csc.calpoly.edu/~zwood/teaching/csc570/final07/dalum_gzipkin/

It helps me a lot， thank you very much！
